# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fiesta-demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://fiesta.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_c9a749483000432e911fb622086af596 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7b2fdb6f544342faa6a5cf55fc44302a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: fiesta.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c9a749483000432e911fb622086af596 }}/fiesta-demo:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fiesta-demo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b4945d46ca5b49499d3f542f50770062 }}
        images: 'fiesta.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c9a749483000432e911fb622086af596 }}/fiesta-demo:${{ github.sha }}'